spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmarkit
    username: app
    password: ybigta4321
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: mq
    password: secret

security:
  enabled: false

logging:
  level:
    root: info
